name: AllergyLab CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build web-app
      run: docker build ./app -t bhliv1691/al-app:latest
    - name: docker build db-loader
      run: docker build ./db-loader -t bhliv1691/al-db-loader:latest
    - name: docker build email
      run: docker build ./email -t bhliv1691/al-email:latest
