name: AllergyLab CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build web-app
      run: docker build ./app -t bhliv1691/al-app:latest
    - name: docker build db-loader
      run: docker build ./db-loader -t bhliv1691/al-db-loader:latest
    - name: docker build email
      run: docker build ./email -t bhliv1691/al-email:latest
    - name: docker-push
      run: |
        docker push bhliv1691/al-app:latest
        docker push bhliv1691/al-db-loader:latest
        docker push bhliv1691/al-email:latest
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: '**PLACEHOLDER** Deploy to Kubernetes'
      run: echo Placeholder for Deployment
    - name: run containers
      run: |
        docker run -d bhliv1691/al-app:latest
        docker run -d bhliv1691/al-db-loader:latest
        docker run -d bhliv1691/al-email:latest
